# -*- coding: utf-8 -*-
"""Predictive Analytics .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NwbA4qAXknhVtnBgTDJKev-0qkI1deQV
"""

!pip install pandas matplotlib scikit-learn

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Study hours and marks dataset

data = {
    'Hours': [1,2,3,4,5,6,7,8],
    'Marks': [35,40,50,55,60,70,80,90]
}

# Create DataFrame

df = pd.DataFrame(data)

print(df)

plt.scatter(
    df['Hours'],
    df['Marks'],
    color='blue'
)

plt.title("Study Hours vs Marks")
plt.xlabel("Study Hours")
plt.ylabel("Marks")

plt.show()

# Input feature

X = df[['Hours']]

# Output target

y = df['Marks']

# Create model

model = LinearRegression()

# Train model

model.fit(X, y)

print("Model Training Completed")

# Predict marks for 9 study hours

prediction = model.predict([[9]])

print("Predicted Marks:", prediction[0])

# Prediction line

plt.scatter(
    df['Hours'],
    df['Marks'],
    color='red'
)

plt.plot(
    df['Hours'],
    model.predict(X)
)

plt.title("Predictive Analytics")
plt.xlabel("Study Hours")
plt.ylabel("Marks")

plt.show()

